---
- name: "Neovim: ensure Neovim - clone"
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ home_path }}/repos/neovim"
    force: true
    depth: 1

- name: "Neovim: ensure neovim build dependencies"
  become: true
  ansible.builtin.package:
    name:
      - cmake
      - ninja

- name: "Neovim: apply folds patch to neovim"
  ansible.posix.patch:
    src: "{{ home_path }}/dotfiles/nvim/patches/folds.patch"
    dest: "{{ home_path }}/repos/neovim/src/nvim/drawline.c"
    basedir: "{{ home_path }}/repos/neovim"
    state: present

- name: "Neovim: ensure neovim - build"
  ansible.builtin.command: make
  become: true
  environment:
    CMAKE_BUILD_TYPE: RelWithDebInfo
  args:
    chdir: "{{ home_path }}/repos/neovim"

- name: "Neovim: ensure neovim - install"
  become: true
  ansible.builtin.command: make install
  args:
    chdir: "{{ home_path }}/repos/neovim"
