---
- name: Ensure ansible aur module is installed
  ansible.builtin.include_tasks: setup-aur.{{ user_os }}.yml

- name: Ensure dotfiles are setup
  ansible.builtin.include_tasks: setup-dotfiles.{{ user_os }}.yml

- name: Ensure peripheral tools are configured
  ansible.builtin.include_tasks: setup-{{ item }}-tools.{{ user_os }}.yml
  loop:
    - keyboard
    - graphic-tablet

- name: Ensure display tools are configured
  ansible.builtin.include_tasks: setup-{{ item }}-tools.{{ user_os }}.yml
  loop:
    - nvidia

- name: Ensure handy utilities are installed
  ansible.builtin.include_tasks: setup-{{ item }}-tools.{{ user_os }}.yml
  loop:
    - automation
    - grep

- name: Ensure compositor is installed
  ansible.builtin.include_tasks: setup-compositor.{{ user_os }}.yml

- name: Ensure browser tools are setup
  ansible.builtin.include_tasks: setup-{{ item }}-tools.{{ user_os }}.yml
  loop:
    - chrome

- name: Ensure wine tools are setup
  ansible.builtin.include_tasks: setup-{{ item }}-tools.{{ user_os }}.yml
  loop:
    - wine
    - yabridge
