---
- name: "{{ item }} tools: enable multilib repository"
  become: true
  ansible.builtin.blockinfile:
    dest: /etc/pacman.conf
    insertafter: '(?m)^#\[multilib\]\n#Include'
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: "{{ item }} tools: ensure wine is installed"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - wine-staging
      - wine-mono

- name: "{{ item }} tools: ensure wine graphic driver"
  become: true
  ansible.builtin.package:
    state: present
    name: lib32-nvidia-utils

- name: "{{ item }} tools: ensure wine audio drivers"
  become: true
  ansible.builtin.package:
    state: present
    name: lib32-pipewire
