---
- name: "AUR: ensure aur - Create modules folder"
  ansible.builtin.file:
    state: directory
    recurse: true
    path: "{{ home_path }}/.ansible/plugins/modules"

- name: "AUR: ensure ansible aur helper"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/kewlfft/ansible-aur/master/plugins/modules/aur.py
    dest: "{{ home_path }}/.ansible/plugins/modules/aur.py"
    mode: 0644
