---
- name: "Dotfiles: ensure stow installed"
  ansible.builtin.package:
    state: present
    name: stow

- name: "Dotfiles: apply stow"
  ansible.builtin.shell: stow --dotfiles {{ package }}
  loop_control:
    loop_var: package
  loop:
    - dunst
    - fish
    - gnupg
    - kitty
    - lazygit
    - nvim
    - peripherals
    - pipewire
    - playbooks
    - systemd
    - tmux
    - wireplumber
    - home
    - utilities
  args:
    chdir: "{{ home_path }}/dotfiles"
