---
cpptools_version: v1.32.2
bash_debug_adapter_version: 0.3.7
vscode_js_debug_version: 1.117.0
arch_superhtml_version: 0.5.3
noise_suppression_for_voice_version: "1.10"
ansible_lint_version: 26.8.0
vscode_go_version: "0.56.0"
node_javascript_npm_prefix: "{{ ansible_facts.env.HOME }}/data/apps/lang-tools/javascript-tools/.npm"
node_ansible_language_server_npm_prefix: "{{ ansible_facts.env.HOME }}/data/apps/lang-tools/ansible-language-server/.npm"
node_ansible_language_server_npm_packages:
  - name: "@ansible/ansible-language-server"
    version: 26.6.0
node_javascript_npm_packages:
  - name: eslint
    version: 10.8.1
    bins:
      - eslint
  - name: eslint_d
    version: 15.0.3
    bins:
      - eslint_d
  - name: js-beautify
    version: 2.0.3
    bins:
      - js-beautify
      - css-beautify
      - html-beautify
  - name: typescript
    version: 7.0.2
    bins:
      - tsc
  - name: "@vtsls/language-server"
    version: 0.3.0
    bins:
      - vtsls
  - name: "@tailwindcss/language-server"
    version: 0.16.0
    bins:
      - tailwindcss-language-server
  - name: "@vue/language-server"
    version: 3.3.9
    bins:
      - vue-language-server
node_vim_npm_prefix: "{{ ansible_facts.env.HOME }}/data/apps/lang-tools/vim-tools/.npm"
node_vim_npm_packages:
  - name: vim-language-server
    version: 2.3.1
    bins:
      - vim-language-server
node_html_npm_prefix: "{{ ansible_facts.env.HOME }}/data/apps/lang-tools/html-tools/.npm"
node_html_npm_packages:
  - name: vscode-langservers-extracted
    version: 4.10.0
    bins:
      - vscode-css-language-server
      - vscode-eslint-language-server
      - vscode-html-language-server
      - vscode-json-language-server
      - vscode-markdown-language-server
node_markdown_npm_prefix: "{{ ansible_facts.env.HOME }}/data/apps/note-taking-tools/utilities/.npm"
node_markdown_npm_packages:
  - name: "@mermaid-js/mermaid-cli"
    version: 11.16.0
    bins:
      - mmdc
  - name: mermaid-filter
    version: 1.4.7
    bins:
      - mermaid-filter
  - name: mathjax-pandoc-filter
    version: 0.4.1
    bins:
      - mathjax-pandoc-filter
  - name: markdownlint-cli
    version: 0.49.1
    bins:
      - markdownlint
