---
pipewire_latency_vars:
  PIPEWIRE_LATENCY: "512/48000"
  PIPEWIRE_QUANTUM: "512/48000"
  PIPEWIRE_RATE: "1/48000"

arch_wineasio_setup:
  repo: https://github.com/wineasio/wineasio
  repo_path: "{{ ansible_facts.env.HOME }}/data/repos/wineasio"
  version: master
  reaper_audio_mode: 2
  reaper_block_size: 512
  reaper_sample_rate: 48000

arch_reaper_sws_extension_setup:
  version: 2.14.0.7
  backup_path: ~/data/Downloads/music-production

arch_helgobox_setup:
  version: 2.18.2
  backup_path: ~/data/Downloads/music-production
  linux_vst_name: helgobox-linux-x86_64.so
  linux_vst_checksum: sha256:b23e9a8b6471551a073327bac2f045d6ad296bb593b7157cc944fc4b4e8a5a6e
  linux_reaper_extension_name: reaper_helgobox-linux-x86_64.so
  linux_reaper_extension_checksum: sha256:bd2e44616f3ffd64a3c0f349b4276e17abf214012486a5f49277c632d40f068f

arch_linvst_setup:
  version: "4.9"
  archive_name: LinVst-4.9-wine-10.x-arch.zip
  archive_url: https://github.com/osxmidi/LinVst/releases/download/4.9/LinVst-4.9-wine-10.x-arch.zip
  archive_checksum: sha256:08a09b3f6311ef695d5fb3fa90e883b945ae8cef8977dfa9506a9cabf9b1aff4
  install_parent_path: "{{ ansible_facts.env.HOME }}/.local/share"
  install_path: "{{ ansible_facts.env.HOME }}/.local/share/LinVst-4.9-wine-10.x-arch"
  linvst_so_path: "{{ ansible_facts.env.HOME }}/.local/share/LinVst-4.9-wine-10.x-arch/linvst.so"

arch_linvst3_setup:
  version: "4.9"
  archive_name: LinVst3-4.9-wine-10.x-arch.zip
  archive_url: https://github.com/osxmidi/LinVst3/releases/download/4.9/LinVst3-4.9-wine-10.x-arch.zip
  archive_checksum: sha256:87b9ec1ae800ac955204543728844af7f94fb5c424bb59672062c83b2f7c3f0b
  install_parent_path: "{{ ansible_facts.env.HOME }}/.local/share"
  install_path: "{{ ansible_facts.env.HOME }}/.local/share/LinVst3-4.9-wine-10.x-arch"
  linvst3_so_path: "{{ ansible_facts.env.HOME }}/.local/share/LinVst3-4.9-wine-10.x-arch/linvst3.so"

wwine_prefix_aliases:
  reaper:
    path: "{{ arch_reaper_wine_setup.wine_prefix }}"
    architecture: "{{ arch_reaper_wine_setup.architecture | default('win64') }}"
    sandbox_profile: "{{ ansible_facts.env.HOME }}/.config/firejail/wine-reaper.local"
    sandbox_check_profile: "{{ ansible_facts.env.HOME }}/.local/share/wwine/firejail-profiles/wine-reaper.local"
    sandbox_name: wwine-reaper
  synthv:
    path: "{{ arch_synthv_wine_prefix }}"
    architecture: win64

arch_synthv_wine_prefix: "{{ ansible_facts.env.HOME }}/data/.wine-win64-synthv2"

arch_reaper_wine_setup:
  version: "766"
  backup_path: ~/data/Downloads/music-production
  wine_prefix: "{{ ansible_facts.env.HOME }}/data/.wine-win64-reaper"
  architecture: win64 # wow64 will fail for some plugins

arch_audiogridder_wine_setup:
  version: 1.1.1
  version_slug: "1_1_1"
  plugin_version: 1.1.1
  plugin_version_slug: "1_1_1"
  backup_path: ~/data/Downloads/music-production
  config_path: "{{ ansible_facts.env.HOME }}/data/.wine-win64-reaper/drive_c/users/{{ ansible_facts.env.USER }}/AppData/Roaming/AudioGridder"
  wine_prefix: "{{ ansible_facts.env.HOME }}/data/.wine-win64-reaper"
