---
debian_stow_version: 2.4.1
macos_stow_version: 2.4.1
debian_fzf_version: 0.55.0
debian_rg_version: 14.0.3
debian_fd_version: 10.1.0
arch_mypaint_version: 2.1.0-alpha-400-g90b36db-2021-05-04_18.41
arch_davinci_resolve_version: 19.1.4
wacom_vendor_id: 056a
ansible_hhkb_keyboard_id: 04fe:0021 # same id for hhkb_1, hhkb_2, etc
ansible_mx_keys_keyboard_id: 046d:408a
ansible_internal_keyboard_name_1: AT Translated Set 2 keyboard
ansible_internal_keyboard_name_2: ITE Tech. Inc. ITE Device(8910) Keyboard
ansible_internal_keyboard_name_3: Ideapad extra buttons
ansible_internal_keyboard_device_1: 0001:0001 # this line is required to disable internal keyboard
ansible_internal_keyboard_device_2: 048d:c100 # this line is required to disable internal keyboard
extension_react_devtools: nipckbchhibgnbgnabineijogaiegchd
extension_show_tab_numbers: egbdjbfggjldijfoahggfipdkpijmmgd # local
extension_chrome_regex_search: bpelaihoicobbkgmhcbikncnpacdbknn
extension_floccus: fnaicdffflnofjppbagibeoednhnbjhg
extension_memex: abkfbakhjpmblaafnpgjppbmioombali
extension_new_tab_redirect: jbkaalaijhbkmaffefakjjpphiefocai # local
extension_vimium: dblffdcabmecmgepoideebngccnllhlo # local
extension_hypothesis: bjfhmglciegochdpefhhlphglcehbmek
extension_promnesia: dmeifochafhcoiolkeadbjgimpamfghc # local
chromium_local_extensions:
  - NewTab-Redirect
  - vimium
  - chrome-show-tab-numbers

# backup files
config_files_backup_env: # home folder only
  - ~/.local/share/nvim/trailblazer
  - ~/.local/share/nvim/dirsession
  - ~/.local/share/nvim/fzf-lua
  - ~/.local/share/nvim/gp
  - ~/.local/share/zoxide
  - ~/.cache/nvim/fundo
  - ~/.cache/nvim/undodir
  - ~/.cache/nvim/shadadir
  - ~/.cache/nvim/gp
  - ~/.local/state/nvim/shada
  - ~/.local/share/fish/fish_history
  - ~/.ssh/config
  - ~/.bash_history
  - ~/.config/REAPER
pkm_backup_env:
  - ~/PKM
seedvault_main_backup_env:
  - /storage/emulated/0/.SeedVaultAndroidBackup
phone_photos_backup_env:
  - /storage/emulated/0/DCIM/Camera
notes_backup_env:
  - ~/.local/share/Cryptomator/mnt/foam
reader_annotations_backup_env:
  - /storage/emulated/0/note
root_backup_env:
  - /etc/hosts
  - /etc/ansible/hosts
  - /etc/default/grub
  - /etc/udev/udev.conf
  - /etc/default/cpupower
  - /etc/sysctl.d/99-sysctl.conf
  - /etc/sysctl.d/90-max_user_watches.conf
  - /etc/security/limits.d/95-pipewire.conf
  - /etc/makepkg.conf
  - /etc/mkinitcpio.conf
  - /etc/fstab
  - /etc/X11/xorg.conf.d/80-igpu-primary-egpu-offload.conf
  - /var/log/pacman.log
  - /var/log/journal
bw_backup_env:
  - ~/bw

# borg repos
dev1_config_files_borg_repo: ssh://borg/~/backups/config-files
dev1_pkm_borg_repo: ssh://borg/~/backups/PKM
dev1_notes_borg_repo: ssh://borg/~/backups/notes
dev1_seedvault_borg_repo: ssh://borg/~/backups/seedvault-main
dev1_phone_photos_borg_repo: ssh://borg/~/backups/phone-photos
dev1_reader_annotations_borg_repo: ssh://borg/~/backups/reader-annotations
dev1_root_borg_repo: ssh://borg/~/backups/root-backup
dev1_bw_borg_repo: ssh://borg/~/backups/bw-backup
dev2_config_files_borg_repo: /run/media/serranomorante/Data/backups/config-files
dev2_pkm_borg_repo: /run/media/serranomorante/Data/backups/PKM
dev2_notes_borg_repo: /run/media/serranomorante/Data/backups/notes
dev2_root_borg_repo: /run/media/serranomorante/Data/backups/root-backup
dev2_bw_borg_repo: /run/media/serranomorante/Data/backups/bw-backup
dev3_config_files_borg_repo: /run/media/serranomorante/TOSHIBA EXT/backups/config-files
dev3_pkm_borg_repo: /run/media/serranomorante/TOSHIBA EXT/backups/PKM
dev3_notes_borg_repo: /run/media/serranomorante/TOSHIBA EXT/backups/notes
dev3_root_borg_repo: /run/media/serranomorante/TOSHIBA EXT/backups/root-backup
dev3_bw_borg_repo: /run/media/serranomorante/TOSHIBA EXT/backups/bw-backup

otherlinux_borg_repos_env:
  - { repo: "{{ dev1_seedvault_borg_repo }}", pass_file: moonland3344.gpg, files: "{{ seedvault_main_backup_env }}", sh_template: autogenerated-dev1-seedvault-main }
  - { repo: "{{ dev1_phone_photos_borg_repo }}", pass_file: capsule2436.gpg, files: "{{ phone_photos_backup_env }}", sh_template: autogenerated-dev1-phone-photos }
  - { repo: "{{ dev1_reader_annotations_borg_repo }}", pass_file: unreeling3484.gpg, files: "{{ reader_annotations_backup_env }}", sh_template: autogenerated-dev1-reader-annotations }

archlinux_borg_repos_env:
  - { repo: "{{ dev1_config_files_borg_repo }}", pass_file: staunch4647.gpg, files: "{{ config_files_backup_env }}", sh_template: autogenerated-dev1-config-files }
  - { repo: "{{ dev1_pkm_borg_repo }}", pass_file: feed4999.gpg, files: "{{ pkm_backup_env }}", sh_template: autogenerated-dev1-PKM }
  - { repo: "{{ dev1_notes_borg_repo }}", pass_file: clench9629.gpg, files: "{{ notes_backup_env }}", sh_template: autogenerated-dev1-notes }
  - { repo: "{{ dev1_bw_borg_repo }}", pass_file: gummy8889.gpg, files: "{{ bw_backup_env }}", sh_template: autogenerated-dev1-bw-backup }
  - { repo: "{{ dev2_config_files_borg_repo }}", pass_file: staunch4647.gpg, files: "{{ config_files_backup_env }}", sh_template: autogenerated-dev2-config-files }
  - { repo: "{{ dev2_pkm_borg_repo }}", pass_file: feed4999.gpg, files: "{{ pkm_backup_env }}", sh_template: autogenerated-dev2-PKM }
  - { repo: "{{ dev2_notes_borg_repo }}", pass_file: clench9629.gpg, files: "{{ notes_backup_env }}", sh_template: autogenerated-dev2-notes }
  - { repo: "{{ dev2_bw_borg_repo }}", pass_file: gummy8889.gpg, files: "{{ bw_backup_env }}", sh_template: autogenerated-dev2-bw-backup }
  - { repo: "{{ dev3_config_files_borg_repo }}", pass_file: staunch4647.gpg, files: "{{ config_files_backup_env }}", sh_template: autogenerated-dev3-config-files }
  - { repo: "{{ dev3_pkm_borg_repo }}", pass_file: feed4999.gpg, files: "{{ pkm_backup_env }}", sh_template: autogenerated-dev3-PKM }
  - { repo: "{{ dev3_notes_borg_repo }}", pass_file: clench9629.gpg, files: "{{ notes_backup_env }}", sh_template: autogenerated-dev3-notes }
  - { repo: "{{ dev3_bw_borg_repo }}", pass_file: gummy8889.gpg, files: "{{ bw_backup_env }}", sh_template: autogenerated-dev3-bw-backup }

archlinux_borg_root_repos_env:
  - { borg_repo: "{{ dev1_root_borg_repo }}", encrypted_passphrase_file: eloquence1688.gpg, files: "{{ root_backup_env }}", sh_template: autogenerated-dev1-root }
  - { borg_repo: "{{ dev2_root_borg_repo }}", encrypted_passphrase_file: eloquence1688.gpg, files: "{{ root_backup_env }}", sh_template: autogenerated-dev2-root }
  - { borg_repo: "{{ dev3_root_borg_repo }}", encrypted_passphrase_file: eloquence1688.gpg, files: "{{ root_backup_env }}", sh_template: autogenerated-dev3-root }
