---
debian_stow_version: 2.4.1
debian_fzf_version: 0.55.0
wacom_vendor_id: 056a
extension_react_devtools: nipckbchhibgnbgnabineijogaiegchd    # copy from chrome://extensions
extension_bitwarden: nngceckbapebfimnlniiiahkandclblb         # copy from chrome://extensions
extension_show_tab_numbers: egbdjbfggjldijfoahggfipdkpijmmgd  # copy from chrome://extensions
extension_floccus: fnaicdffflnofjppbagibeoednhnbjhg           # copy from chrome://extensions
extension_memex: abkfbakhjpmblaafnpgjppbmioombali             # copy from chrome://extensions
extension_new_tab_redirect: jbkaalaijhbkmaffefakjjpphiefocai  # copy from chrome://extensions
extension_vimium: dblffdcabmecmgepoideebngccnllhlo            # copy from chrome://extensions
chromium_local_extensions:
  - NewTab-Redirect
  - vimium
  - chrome-show-tab-numbers
home_config_data_backups:
  - .local/share/nvim/trailblazer         # trailblazer marks
  - .local/share/nvim/dirsession          # resession
  - .local/share/nvim/fzf-lua             # fzf lua history
  - .local/share/nvim/gp                  # chat gpt
  - .cache/nvim/fundo                     # nvim fundo
  - .cache/nvim/undodir                   # undo history
  - .cache/nvim/shadadir                  # shada file
  - .cache/nvim/gp
  - .local/state/nvim/shada
  - .local/share/fish/fish_history        # fish history
