---
debian_stow_version: 2.4.1
debian_fzf_version: 0.55.0
wacom_vendor_id: 056a
extension_react_devtools: nipckbchhibgnbgnabineijogaiegchd
extension_bitwarden: nngceckbapebfimnlniiiahkandclblb
extension_show_tab_numbers: egbdjbfggjldijfoahggfipdkpijmmgd # local
extension_floccus: fnaicdffflnofjppbagibeoednhnbjhg
extension_memex: abkfbakhjpmblaafnpgjppbmioombali
extension_new_tab_redirect: jbkaalaijhbkmaffefakjjpphiefocai # local
extension_vimium: dblffdcabmecmgepoideebngccnllhlo # local
extension_hypothesis: bjfhmglciegochdpefhhlphglcehbmek
extension_promnesia: dmeifochafhcoiolkeadbjgimpamfghc # local
chromium_local_extensions:
  - NewTab-Redirect
  - vimium
  - chrome-show-tab-numbers
config_files_backup_env:
  - ~/.local/share/nvim/trailblazer
  - ~/.local/share/nvim/dirsession
  - ~/.local/share/nvim/fzf-lua
  - ~/.local/share/nvim/gp
  - ~/.cache/nvim/fundo
  - ~/.cache/nvim/undodir
  - ~/.cache/nvim/shadadir
  - ~/.cache/nvim/gp
  - ~/.local/state/nvim/shada
  - ~/.local/share/fish/fish_history
pkm_backup_env:
  - ~/PKM
seedvault_main_backup_env:
  - /storage/emulated/0/.SeedVaultAndroidBackup
dev1_config_files_borg_repo: ssh://borg/~/backups/config-files
dev1_pkm_borg_repo: ssh://borg/~/backups/PKM
dev1_seedvault_borg_repo: ssh://borg/~/backups/seedvault-main
dev2_config_files_borg_repo: /run/media/serranomorante/Data/backups/config-files
dev2_pkm_borg_repo: /run/media/serranomorante/Data/backups/PKM
dev3_config_files_borg_repo: /run/media/serranomorante/TOSHIBA EXT/backups/config-files
dev3_pkm_borg_repo: /run/media/serranomorante/TOSHIBA EXT/backups/PKM
