---
debian_stow_version: 2.4.1
debian_fzf_version: 0.55.0
wacom_vendor_id: 056a
extension_react_devtools: nipckbchhibgnbgnabineijogaiegchd
extension_bitwarden: nngceckbapebfimnlniiiahkandclblb
extension_show_tab_numbers: egbdjbfggjldijfoahggfipdkpijmmgd # local
extension_floccus: fnaicdffflnofjppbagibeoednhnbjhg
extension_memex: abkfbakhjpmblaafnpgjppbmioombali
extension_new_tab_redirect: jbkaalaijhbkmaffefakjjpphiefocai # local
extension_vimium: dblffdcabmecmgepoideebngccnllhlo # local
extension_hypothesis: bjfhmglciegochdpefhhlphglcehbmek
extension_promnesia: dmeifochafhcoiolkeadbjgimpamfghc # local
chromium_local_extensions:
  - NewTab-Redirect
  - vimium
  - chrome-show-tab-numbers
systemd_config_backups_dirs:
  - "%h/.local/share/nvim/trailblazer"         # trailblazer marks
  - "%h/.local/share/nvim/dirsession"          # resession
  - "%h/.local/share/nvim/fzf-lua"             # fzf lua history
  - "%h/.local/share/nvim/gp"                  # chat gpt
  - "%h/.cache/nvim/fundo"                     # nvim fundo
  - "%h/.cache/nvim/undodir"                   # undo history
  - "%h/.cache/nvim/shadadir"                  # shada file
  - "%h/.cache/nvim/gp"
  - "%h/.local/state/nvim/shada"
  - "%h/.local/share/fish/fish_history"        # fish history
  - /etc/ansible/hosts
