# https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Virtual-Devices#coupled-streams
context.modules = [
  {
    name = libpipewire-module-loopback
    args = {
      audio.position = [ FL FR ]
      capture.props = {
        media.class = Audio/Sink
        node.name = "capture.sink_node.multimedia"
        node.description = "[sink node] multimedia"
        audio.rate = 48000
      }
      playback.props = {
        node.name = "sink_node.multimedia"
        node.passive = true
        audio.rate = 48000
      }
    }
  }
  {
    name = libpipewire-module-loopback
    args = {
      audio.position = [ FL FR ]
      capture.props = {
        media.class = Audio/Sink
        node.name = "capture.sink_node.work"
        node.description = "[sink node] work"
        audio.rate = 48000
      }
      playback.props = {
        node.name = "sink_node.work"
        node.passive = true
        audio.rate = 48000
      }
    }
  }
  {
    name = libpipewire-module-loopback
    args = {
      audio.position = [ FL FR ]
      capture.props = {
        media.class = Audio/Sink
        node.name = "capture.sink_node.music-production"
        node.description = "[sink node] music production"
        audio.rate = 48000
      }
      playback.props = {
        node.name = "sink_node.music-production"
        node.passive = true
        audio.rate = 48000
      }
    }
  }
]
