---
- name: "Note-taking utilities: ensure packages"
  become: true
  ansible.builtin.package:
    state: present
    name: pandoc

- name: "Note-taking utilities: ensure virtualenv packages"
  ansible.builtin.pip:
    name:
      - pip
      - weasyprint
    virtualenv: ~/apps/note-taking-tools/utilities/.venv
    virtualenv_command: /usr/bin/python3 -m venv
    state: latest

- name: "Note-taking utilities: symlink utilities"
  ansible.builtin.file:
    src: ~/apps/note-taking-tools/utilities/.venv/bin/{{ item }}
    dest: ~/bin/{{ item }}
    state: link
  loop:
    - weasyprint
