gui:
  scrollHeight: 8
  nerdFontsVersion: "3"
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 5
  skipRewordInEditorWarning: true
  showDivergenceFromBaseBranch: "arrowAndNumber"
  filterMode: "fuzzy"
# based on: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#default
keybinding:
  universal:
    quit: <disabled>
# based on: https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md#delta
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  autoStageResolvedConflicts: false
  paging:
    colorArg: always
    # uncomment if you want to use difftastic
    # externalDiffCommand: difft --color=always
    useConfig: true
# based on: https://github.com/jesseduffield/lazygit/issues/996#issuecomment-1624329763
os:
  edit: 'nvr --servername $CUSTOM_NVIM_LISTEN_ADDRESS --nostart --remote {{filename}} | tmux select-window -t {start}\; if-shell -F "#{&&:#{>:#{pane_index},0},#{window_zoomed_flag}}" "resize-pane -Z" "" \; select-pane -t {top-left}'
  editAtLine: 'nvr --servername $CUSTOM_NVIM_LISTEN_ADDRESS --nostart --remote {{filename}} -c "{{line}}" | tmux select-window -t {start}\; if-shell -F "#{&&:#{>:#{pane_index},0},#{window_zoomed_flag}}" "resize-pane -Z" "" \; select-pane -t {top-left}'
  editAtLineAndWait: 'nvr --servername $CUSTOM_NVIM_LISTEN_ADDRESS --nostart --remote-wait {{filename}} -c "{{line}}" | tmux select-window -t {start}\; if-shell -F "#{&&:#{>:#{pane_index},0},#{window_zoomed_flag}}" "resize-pane -Z" "" \; select-pane -t {top-left}'
  editInTerminal: false
  open: 'nvr --servername $CUSTOM_NVIM_LISTEN_ADDRESS --nostart --remote {{filename}} | tmux select-window -t {start}\; if-shell -F "#{&&:#{>:#{pane_index},0},#{window_zoomed_flag}}" "resize-pane -Z" "" \; select-pane -t {top-left}'
  openDirInEditor: 'nvr --servername $CUSTOM_NVIM_LISTEN_ADDRESS --nostart {{dir}} | tmux select-window -t {start}\; if-shell -F "#{&&:#{>:#{pane_index},0},#{window_zoomed_flag}}" "resize-pane -Z" "" \; select-pane -t {top-left}'
promptToReturnFromSubprocess: false
notARepository: 'quit'
customCommands:
  # From local branches, compare selected branch against checked out branch
  - key: "D"
    description: "Custom: Compare selected branch against checked out branch"
    context: "localBranches"
    command: 'nvr --servername $CUSTOM_NVIM_LISTEN_ADDRESS --nostart -c "DiffviewFileHistory --range=HEAD...{{ .SelectedLocalBranch.Name }} --right-only --no-merges" | tmux select-window -t {start}\; if-shell -F "#{&&:#{>:#{pane_index},0},#{window_zoomed_flag}}" "resize-pane -Z" "" \; select-pane -t {top-left}'
  # From commits, search the whole history for an expression in a file (case-sensitive)
  - key : '<c-a>'
    description: 'Custom: Search the whole history (from a ref and down) for an expression in a file'
    command: "git checkout {{index .PromptResponses 3}}"
    context: 'commits,subCommits'
    prompts:
      - type: 'input'
        title: 'Search word:'
      - type: 'input'
        title: 'File/Subtree:'
      - type: 'input'
        title: 'Ref:'
        initialValue: "{{index .CheckedOutBranch.Name }}"
      - type: 'menuFromCommand'
        title: 'Commits:'
        command: "git log --oneline {{index .PromptResponses 2}} -S'{{index .PromptResponses 0}}' --all -- {{index .PromptResponses 1}}"
        filter: '(?P<commit_id>[0-9a-zA-Z]*) *(?P<commit_msg>.*)'
        valueFormat: '{{ .commit_id }}'
        labelFormat: '{{ .commit_id | green | bold }} - {{ .commit_msg | yellow }}'
  # From commits, add empty commit
  - key: 'E'
    description: 'Custom: Add empty commit'
    context: 'commits,files'
    command: 'git commit --allow-empty -m "empty commit"'
    loadingText: 'Committing empty commit...'
  # From files, open mergetool (DiffviewOpen)
  - key: "M"
    description: 'Custom: Open mergetool'
    command: 'nvr --servername $CUSTOM_NVIM_LISTEN_ADDRESS --nostart --remote {{ .SelectedFile.Name }} -c "DiffviewOpen" | tmux select-window -t {start}\; if-shell -F "#{&&:#{>:#{pane_index},0},#{window_zoomed_flag}}" "resize-pane -Z" "" \; select-pane -t {top-left}'
    context: "files"
    loadingText: "loading DiffviewOpen"
    subprocess: true
  # From commits, extract diff into /tmp/<sha>.patch file
  - key: '<c-q>'
    command: git diff {{.SelectedCommit.Sha}}^! > /tmp/{{.SelectedCommit.Sha}}.patch
    context: "commits,subCommits"
    description: 'Custom: extract commit diff into /tmp/<sha>.patch file'
  # From files, open difftool (DiffviewOpen)
  - key: "<c-t>"
    description: 'Custom: Open difftool'
    command: 'nvr --servername $CUSTOM_NVIM_LISTEN_ADDRESS --nostart --remote {{ .SelectedFile.Name }} -c "DiffviewOpen" | tmux select-window -t {start}\; if-shell -F "#{&&:#{>:#{pane_index},0},#{window_zoomed_flag}}" "resize-pane -Z" "" \; select-pane -t {top-left}'
    context: "files"
    loadingText: "loading DiffviewOpen"
    subprocess: true
  # From commits, push a specific commit (and any preceding)
  - key: 'P'
    description: 'Custom: Force push a specific commit (and any preceding)'
    command: "git push --force {{.SelectedRemote.Name}} {{.SelectedCommit.Sha}}:{{.SelectedLocalBranch.Name}}"
    context: "commits"
    loadingText: "Pushing commit..."
    stream: true
    prompts:
      - type: "confirm"
        key: "Confirm"
        title: "Force push specific commit"
        body: "Are you sure you want to force push?"
  # From commits, open as a PR review
  - key: 'D'
    description: 'Custom: Diff commit against parent commit'
    command: 'nvr --servername $CUSTOM_NVIM_LISTEN_ADDRESS --nostart -c "DiffviewOpen {{.SelectedCommit.Sha}}^!" | tmux select-window -t {start}\; if-shell -F "#{&&:#{>:#{pane_index},0},#{window_zoomed_flag}}" "resize-pane -Z" "" \; select-pane -t {top-left}'
    context: "commits,subCommits"
  # From remotes, fetch a remote branch as a new local branch
  - key: '<c-f>'
    description: 'Custom: fetch a remote branch as a new local branch'
    command: "git fetch {{index .SelectedRemote.Name }} {{index .PromptResponses 0}}:{{index .PromptResponses 1}}"
    context: 'remotes'
    prompts:
      - type: 'input'
        title: 'Remote Branch Name'
        initialValue: ''
      - type: 'input'
        title: 'New Local Branch Name'
        initialValue: ''
    loadingText: 'fetching branch'
  # From commitFiles, compare (difftool) with local copy
  - key: 'f'
    description: 'Custom: Compare (difftool) with local copy'
    command: 'nvr --servername $CUSTOM_NVIM_LISTEN_ADDRESS --nostart --remote {{.SelectedCommitFile.Name}} -c "DiffviewOpen {{.SelectedCommit.Sha}} -- %" | tmux select-window -t {start}\; if-shell -F "#{&&:#{>:#{pane_index},0},#{window_zoomed_flag}}" "resize-pane -Z" "" \; select-pane -t {top-left}'
    context: 'commitFiles'
