#!/bin/sh
# {{ ansible_managed }}

{% for repo in archlinux_borg_repos_env %}
borgb -f "{{ repo.keyrings.folder }}" -p "{{ repo.keyrings.passkey }}" -w "{{ repo.keyrings.wallet }}" -- \
    borg key export '{{ repo.repo }}' "{{ ansible_facts.env.HOME }}/data/secrets/backup-borg-keyfiles/{{ repo.device | regex_replace('[^A-Za-z0-9]', '_') }}_data_backups_{{ repo.repo | basename | regex_replace('[^A-Za-z0-9]', '_') }}"

{% endfor %}
