#!/bin/sh
# {{ ansible_managed }}

# This is just a template. The real files are auto-generated by ansible onto the ~/bin/... directory.

export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes

# Setting this, so the repo does not need to be given on the commandline:
export BORG_REPO='{{ borg_repo }}'

# See the section "Passphrase notes" for more infos.
# Check if running under sudo
if [[ -n "${SUDO_USER:-}" ]] && [[ "$EUID" -eq 0 ]]; then
    export BORG_PASSCOMMAND='/usr/local/bin/run_as_user -u {{ ansible_env.USER }} kwallet-query --folder {{ keyrings.folder }} --read-password {{ keyrings.passkey }} {{ keyrings.wallet }}'
else
    export BORG_PASSCOMMAND='kwallet-query --folder {{ keyrings.folder }} --read-password {{ keyrings.passkey }} {{ keyrings.wallet }}'
fi

# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$(date)" "$*" >&2; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup"

# Backup the most important directories into an archive named after
# the machine this script is currently running on:

borg create \
    --verbose \
    --filter AME \
    --list \
    --stats \
    --show-rc \
    --compression lz4 \
    \
    ::'{hostname}-{now:%Y-%m-%d_%H_%M_%S}' \
    {% for dir in files %}
{% if not loop.last %}
{{ dir }} \
    {% else %}
{{ dir }}
{% endif %}
{% endfor %}

backup_exit=$?

info "Pruning repository"

# Use the `prune` subcommand to maintain 7 daily, 4 weekly and 6 monthly
# archives of THIS machine. The '{hostname}-*' matching is very important to
# limit prune's operation to this machine's archives and not apply to
# other machines' archives also:

borg prune \
    --list \
    --glob-archives '{hostname}-*' \
    --show-rc \
    --keep-daily 7 \
    --keep-weekly 4 \
    --keep-monthly 6

prune_exit=$?

# actually free repo disk space by compacting segments

info "Compacting repository"

borg compact

compact_exit=$?

# use highest exit code as global exit code
global_exit=$((backup_exit > prune_exit ? backup_exit : prune_exit))
global_exit=$((compact_exit > global_exit ? compact_exit : global_exit))

if [ ${global_exit} -eq 0 ]; then
    info "Backup, Prune, and Compact finished successfully"
elif [ ${global_exit} -eq 1 ]; then
    info "Backup, Prune, and/or Compact finished with warnings"
else
    info "Backup, Prune, and/or Compact finished with errors"
fi

exit ${global_exit}
