#!/usr/bin/env bash
# {{ ansible_managed }}
set -euo pipefail

"{{ ansible_facts.env.HOME }}/.local/bin/connect-reaper-to-music-production" &
exec kitty --hold -o env=LC_ALL=C {% for env in pipewire_latency_vars.items() %}-o "env={{ env | join('=') }}" {% endfor %} --directory "{{ arch_reaper_wine_setup.wine_prefix }}/dosdevices/c:/Program Files/REAPER (x64)" {{ ansible_facts.env.HOME }}/bin/wwine --prefix reaper --use-sandbox wine "C:/Program Files/REAPER (x64)/REAPER.exe"
