---
- name: Ensure language tools are installed
  # see:  https://github.com/ansible/ansible/issues/30600
  ansible.builtin.include_tasks: setup-{{ item }}-tools.{{ user_os }}.yml
  loop:
    - c
    - lua
    - json
    - javascript
    - fish
    - yaml
    - bash
    - markdown
    - vim
