---
- name: "{{ item }} language: ensure DAP - cpptools folder exists"
  ansible.builtin.file:
    path: "{{ home_path }}/apps/lang-tools/cpptools"
    state: directory
    mode: "0755"

- name: "{{ item }} language: ensure DAP - install cpptools"
  ansible.builtin.unarchive:
    src: https://github.com/microsoft/vscode-cpptools/releases/download/{{ cpptools_1_21 }}/cpptools-linux-x64.vsix
    dest: "{{ home_path }}/apps/lang-tools/cpptools"
    remote_src: true

- name: "{{ item }} language: ensure DAP - set cpptools as executable"
  ansible.builtin.file:
    path: "{{ home_path }}/apps/lang-tools/cpptools/extension/debugAdapters/bin/OpenDebugAD7"
    mode: "0755"
