---
- name: "Fish: ensure LSP - clone fish-lsp"
  ansible.builtin.git:
    repo: https://github.com/ndonfris/fish-lsp.git
    dest: ~/repos/fish-lsp
    depth: 1
    force: true

- name: "Fish: ensure LSP - prepare fish-lsp dependencies"
  ansible.builtin.command: volta install yarn@1.22.22 # needed by the fish-lsp package

- name: "Fish: ensure LSP - install fish-lsp"
  ansible.builtin.command: yarn install
  args:
    chdir: ~/repos/fish-lsp

- name: "Fish: ensure LSP - symlink fish-lsp"
  file:
    src: ~/repos/fish-lsp/bin/fish-lsp
    dest: ~/bin/fish-lsp
    state: link
