---
- name: "Fish: ensure LSP - clone fish-lsp"
  ansible.builtin.git:
    repo: https://github.com/ndonfris/fish-lsp.git
    dest: "{{ home_path }}/repos/fish-lsp"
    depth: 1
    force: true

- name: "Fish: ensure LSP - prepare fish-lsp dependencies"
  ansible.builtin.command: volta install yarn@1.22.22 # needed by the fish-lsp package

- name: "Fish: ensure LSP - install fish-lsp"
  ansible.builtin.command: yarn install
  args:
    chdir: "{{ home_path }}/repos/fish-lsp"

- name: "Fish: ensure LSP - symlink fish-lsp"
  file:
    src: "{{ home_path }}/repos/fish-lsp/bin/fish-lsp"
    dest: "{{ home_path }}/bin/fish-lsp"
    state: link
