---
- name: "{{ item }} language: ensure LSP"
  become: true
  ansible.builtin.package:
    state: present
    name: lua-language-server

- name: "{{ item }} language: ensure FORMATTERS"
  become: true
  ansible.builtin.package:
    state: present
    name: stylua
