---
- name: "[archlinux] Setup node: register volta exists"
  ansible.builtin.command: which volta
  register: volta_executable
  ignore_errors: true
  changed_when: false

- name: "[archlinux] Setup node: install volta"
  ansible.builtin.shell: >
    set -o pipefail &&
    curl https://get.volta.sh | bash -s -- --skip-setup
  when: volta_executable is failed
  changed_when: false

- name: "[archlinux] Setup node: add volta to console startup scripts"
  ansible.builtin.blockinfile:
    dest: "{{ item.script }}"
    create: true
    marker: "## {mark} ANSIBLE MANAGED BLOCK - SETUP NODE"
    mode: "744"
    block: |
      {% if 'dot-bashrc' in item.script %}
      export VOLTA_HOME="$HOME/.volta"
      export PATH="$VOLTA_HOME/bin:$PATH"
      {% endif %}
  loop:
    - { script: ~/dotfiles/home/dot-bashrc }

- name: "[archlinux] Setup node: install node versions"
  ansible.builtin.command: "volta install node@{{ item }}"
  changed_when: false
  loop:
    - "{{ node_system_default_version }}"
    - 21
