---
- name: "[archlinux] Setup node: register volta exists"
  ansible.builtin.command: which volta
  register: volta_executable
  ignore_errors: true
  changed_when: false

- name: "[archlinux] Setup node: install volta"
  ansible.builtin.shell: >
    set -o pipefail &&
    curl https://get.volta.sh | bash -s -- --skip-setup
  when: volta_executable is failed

- name: "[archlinux] Setup node: add volta to console startup scripts"
  ansible.builtin.blockinfile:
    dest: "{{ item.script }}"
    create: true
    marker: "## {mark} ANSIBLE MANAGED BLOCK - SETUP NODE"
    block: |
      {% if 'dot-bashrc' in item.script %}
      export VOLTA_HOME="$HOME/.volta"
      export PATH="$VOLTA_HOME/bin:$PATH"
      {% else %}
      set -gx VOLTA_HOME "$HOME/.volta"
      set -gx PATH "$VOLTA_HOME/bin:$PATH"
      {% endif %}
  loop:
    - { script: ~/dotfiles/home/dot-bashrc }
    - { script: ~/dotfiles/fish/dot-config/fish/conf.d/setup_bashrc.fish }

- name: "[archlinux] Setup node: volta node install system version"
  ansible.builtin.shell: "volta install node@{{ node_system_default_version }}"
