---
- name: "Setup terminal tools: ensure packages"
  ansible.builtin.package:
    name:
      - polkit # https://wiki.archlinux.org/title/Systemd/User#Automatic_start-up_of_systemd_user_instances
      - kitty
      - tmux
      - fish
    state: present

- name: "Setup terminal tools: ensure automatic start-up of systemd user instances"
  ansible.builtin.command: loginctl enable-linger
  changed_when: false

- name: "Setup terminal tools: register default shell"
  ansible.builtin.shell: which fish 
  register: fish_executable
  ignore_errors: true

- name: "Setup terminal tools: change tools configs"
  ansible.builtin.blockinfile:
    dest: "{{ item.script }}"
    create: true
    marker: "## {mark} ANSIBLE MANAGED BLOCK - SETUP {{ item.script|basename|upper }}"
    block: |
      {% if 'tmux.conf' in item.script %}
      set-option -g default-shell {{ fish_executable.stdout }}
      set-option -sa terminal-features ',xterm-kitty:RGB'
      {% elif 'kitty.conf' in item.script %}
      shell {{ fish_executable.stdout }}
      {% endif %}
  loop:
    - { script: ~/dotfiles/tmux/dot-config/tmux/tmux.conf }
    - { script: ~/dotfiles/kitty/dot-config/kitty/kitty.conf }

- name: "Setup terminal tools: fix kdeglobals"
  ansible.builtin.blockinfile:
    dest: ~/.config/kdeglobals
    insertafter: '^\[General\]'
    block: |
      TerminalApplication=kitty
      TerminalService=kitty.desktop

- name: "Setup terminal tools: autostart base tmux sessions with systemd"
  ansible.builtin.systemd_service:
    scope: user
    name: "{{ service }}"
    state: started
    enabled: true
    masked: false
  loop:
    - tmux
    - tmux-overseer
  loop_control:
    loop_var: service
