---
- name: "[archlinux] Setup terminal tools: ensure packages"
  become: true
  ansible.builtin.package:
    name:
      - polkit # https://wiki.archlinux.org/title/Systemd/User#Automatic_start-up_of_systemd_user_instances
      - zoxide
      - libevent
      - bison
      - make
      - kitty-terminfo
    state: present

- name: "[archlinux] Setup terminal tools: uv ensure packages"
  ansible.builtin.command: uv tool install --python=3.12 {{ item.package_name }}
  args:
    creates: "{{ item.creates }}"
  loop:
    - package_name: isd-tui
      creates: ~/.local/bin/isd
    - package_name: vectorcode
      creates: ~/.local/bin/vectorcode

- name: "[archlinux] Setup terminal tools: install kitty nightly"
  ansible.builtin.shell: >
    set -o pipefail &&
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin \
      installer=nightly launch=n
  changed_when: false

- name: "[archlinux] Setup terminal tools: symlink kitty nightly"
  ansible.builtin.file:
    src: ~/.local/kitty.app/bin/{{ item }}
    dest: ~/bin/{{ item }}
    state: link
  loop:
    - kitty
    - kitten

- name: "[archlinux] Setup terminal tools: clone tmux"
  ansible.builtin.git:
    repo: https://github.com/tmux/tmux.git
    dest: ~/repos/tmux
    force: true
    depth: 1
    version: "{{ tmux_version }}"

- name: "[archlinux] Setup terminal tools: run tmux autogen"
  ansible.builtin.command: sh autogen.sh
  args:
    chdir: ~/repos/tmux
    creates: ~/repos/tmux/configure

- name: "[archlinux] Setup terminal tools: configure tmux with sixel enabled"
  ansible.builtin.command: ./configure --enable-sixel
  args:
    chdir: ~/repos/tmux
    creates: ~/repos/tmux/tmux

- name: "[archlinux] Setup terminal tools: run tmux make"
  become: true
  ansible.builtin.shell: make && make install
  args:
    chdir: "{{ ansible_env.HOME }}/repos/tmux"
    creates: /usr/local/bin/tmux

- name: "[archlinux] Setup terminal tools: ensure automatic start-up of systemd user instances"
  ansible.builtin.command: loginctl enable-linger
  changed_when: false

- name: "[archlinux] Setup terminal tools: register default shell"
  ansible.builtin.command: which bash
  register: shell_executable
  ignore_errors: true
  changed_when: false

- name: "[archlinux] Setup terminal tools: change tools configs"
  ansible.builtin.blockinfile:
    dest: "{{ item.script }}"
    create: true
    marker: "## {mark} ANSIBLE MANAGED BLOCK - SETUP {{ item.script | basename | upper }}"
    block: |
      {% if 'tmux.conf' in item.script %}
      set-option -g default-shell {{ shell_executable.stdout }}
      set-option -g default-terminal "xterm-kitty"
      set-option -ag terminal-overrides ",xterm-kitty:RGB"
      {% endif %}
    mode: "644"
  loop:
    - { script: ~/dotfiles/tmux/dot-config/tmux/tmux.conf }

- name: "[archlinux] Setup terminal tools: fix kdeglobals"
  ansible.builtin.blockinfile:
    dest: ~/.config/kdeglobals
    insertafter: "^\\[General\\]"
    block: |
      TerminalApplication=kitty
      TerminalService=kitty.desktop
