---
- name: "[archlinux] Setup terminal tools: ensure packages"
  ansible.builtin.package:
    name:
      - polkit # https://wiki.archlinux.org/title/Systemd/User#Automatic_start-up_of_systemd_user_instances
      - kitty
      - tmux
      - fish
    state: present

- name: "[archlinux] Setup terminal tools: ensure automatic start-up of systemd user instances"
  ansible.builtin.command: loginctl enable-linger
  changed_when: false

- name: "[archlinux] Setup terminal tools: register default shell"
  ansible.builtin.command: which bash
  register: shell_executable
  ignore_errors: true
  changed_when: false

- name: "[archlinux] Setup terminal tools: change tools configs"
  ansible.builtin.blockinfile:
    dest: "{{ item.script }}"
    create: true
    marker: "## {mark} ANSIBLE MANAGED BLOCK - SETUP {{ item.script | basename | upper }}"
    block: |
      {% if 'tmux.conf' in item.script %}
      set-option -g default-shell {{ shell_executable.stdout }}
      set -g default-terminal "xterm-256color" # wezterm uses this term by default
      set -ag terminal-overrides ",xterm-256color:RGB"
      {% endif %}
  loop:
    - { script: ~/dotfiles/tmux/dot-config/tmux/tmux.conf }
    - { script: ~/dotfiles/kitty/dot-config/kitty/kitty.conf }

- name: "[archlinux] Setup terminal tools: fix kdeglobals"
  ansible.builtin.blockinfile:
    dest: ~/.config/kdeglobals
    insertafter: '^\[General\]'
    block: |
      TerminalApplication=kitty
      TerminalService=kitty.desktop

- name: "[archlinux] Setup terminal tools: autostart base tmux sessions with systemd"
  ansible.builtin.systemd_service:
    scope: user
    name: "{{ service }}.service"
    state: started
    enabled: true
    masked: false
  loop:
    - tmux
    - tmux-overseer
  loop_control:
    loop_var: service

- name: "[archlinux] Setup terminal tools: save copy of fish's default prompt"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/fish-shell/fish-shell/refs/heads/master/share/functions/fish_prompt.fish
    dest: ~/.config/fish/functions/fish_prompt_original.fish
    force: true
    mode: "644"

- name: "[archlinux] Setup terminal tools: modify fish's default prompt name"
  ansible.builtin.replace:
    path: ~/.config/fish/functions/fish_prompt_original.fish
    regexp: fish_prompt
    replace: fish_prompt_original
