---
- name: "[archlinux] Setup NVR tools: ensure virtualenv parent directory"
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/data/apps/python-tools"
    state: directory
    mode: "755"

- name: "[archlinux] Setup NVR tools: ensure virtualenv packages"
  ansible.builtin.pip:
    name:
      - pip
      - neovim-remote
    executable: "{{ ansible_facts.env.HOME }}/bin/ansible-firejail-pip"
    state: present
  environment:
    ANSIBLE_FIREJAIL_PIP_VENV: "{{ ansible_facts.env.HOME }}/data/apps/python-tools/.venv"

- name: "[archlinux] Setup NVR tools: symlink virtualenv nvr"
  ansible.builtin.file:
    src: ~/data/apps/python-tools/.venv/bin/{{ item }}
    dest: ~/bin/{{ item }}
    state: link
  loop:
    - nvr

- name: "[archlinux] Setup NVR tools: prepare .desktop and mimetype"
  ansible.builtin.shell: |
    update-desktop-database ~/.local/share/applications
    xdg-mime default nvr_nvim_open.desktop x-scheme-handler/terminal
  changed_when: false
