---
- name: "[archlinux] Setup NVR tools: ensure virtualenv parent directory"
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/data/apps/python-tools"
    state: directory
    mode: "755"

- name: "[archlinux] Setup NVR tools: ensure virtualenv packages"
  ansible.builtin.include_role:
    name: update-diff-capture
    tasks_from: pip
  vars:
    update_diff_capture_scope: nvr-tools
    update_diff_pip_venv: "{{ ansible_facts.env.HOME }}/data/apps/python-tools/.venv"
    update_diff_pip_executable: "{{ ansible_facts.env.HOME }}/bin/ansible-firejail-pip"
    update_diff_pip_packages:
      - name: pip
      - name: neovim-remote

- name: "[archlinux] Setup NVR tools: symlink virtualenv nvr"
  ansible.builtin.file:
    src: ~/data/apps/python-tools/.venv/bin/{{ item }}
    dest: ~/bin/{{ item }}
    state: link
  loop:
    - nvr

- name: "[archlinux] Setup NVR tools: prepare .desktop and mimetype"
  ansible.builtin.shell: |
    update-desktop-database ~/.local/share/applications
    xdg-mime default nvr_nvim_open.desktop x-scheme-handler/terminal
  changed_when: false
