---
- name: "[archlinux] Setup google: ensure packages"
  # You should do: `gcloud init` after
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/10-system-tools/tasks/install-local-aur-packages.archlinux.yml"
  vars:
    aur_local_packages: google-cloud-cli

- name: "[archlinux] Setup google: ensure app directory"
  ansible.builtin.file:
    path: ~/data/apps/dev-tools
    state: directory
    mode: "755"

- name: "[archlinux] Setup google: ensure bin packages"
  # You should do `firebase login` after
  ansible.builtin.get_url:
    url: https://firebase.tools/bin/linux/v{{ firebase_cli_version }}
    dest: ~/data/apps/dev-tools/firebase-{{ firebase_cli_version }}
    mode: "755"

- name: "[archlinux] Setup google: link firebase"
  ansible.builtin.file:
    src: ~/data/apps/dev-tools/firebase-{{ firebase_cli_version }}
    dest: ~/bin/firebase
    state: link
    force: true
