---
- name: "[archlinux] Setup other tools: ensure local AUR packages"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/10-system-tools/tasks/install-local-aur-packages.archlinux.yml"
  vars:
    aur_local_packages: postman-bin
