---
- name: "[archlinux] Neovim: ensure user bin directory"
  ansible.builtin.file:
    path: "{{ node_user_bin_dir }}"
    state: directory
    mode: "755"

- name: "[archlinux] Neovim: ensure firejail profile directory"
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.config/firejail"
    state: directory
    mode: "755"

- name: "[archlinux] Neovim: install firejail profile"
  ansible.builtin.template:
    src: fj-dev-nvim.profile
    dest: "{{ ansible_facts.env.HOME }}/.config/firejail/fj-dev-nvim.profile"
    mode: "644"

- name: "[archlinux] Neovim: install firejail wrapper helper"
  ansible.builtin.copy:
    src: firejail-wrapper-common.bash
    dest: "{{ node_user_bin_dir }}/firejail-wrapper-common.bash"
    mode: "755"

- name: "[archlinux] Neovim: install firejail Neovim wrapper"
  ansible.builtin.copy:
    src: fj-dev-nvim
    dest: "{{ nvim_firejail_executable }}"
    mode: "755"

- name: "[archlinux] Neovim: remove old firejail dev wrappers"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_facts.env.HOME }}/.config/firejail/fj-dev-node.profile"
    - "{{ ansible_facts.env.HOME }}/.config/firejail/fj-dev-python.profile"
    - "{{ node_user_bin_dir }}/fj-dev-node"
    - "{{ node_user_bin_dir }}/fj-dev-python"

- name: "[archlinux] Neovim: ensure Neovim - clone"
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: ~/data/repos/neovim
    force: true
    single_branch: true
    version: "{{ archlinux_neovim_version }}"

- name: "[archlinux] Neovim: ensure neovim build dependencies"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - cmake
      - ninja
      - ccache # recommended here: https://github.com/neovim/neovim/issues/26979#issuecomment-1885240317

- name: "[archlinux] Neovim: remove .deps"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_facts.env.HOME }}/data/repos/neovim/.deps"
    - /usr/local/share/nvim/runtime

- name: "[archlinux] Neovim: ensure neovim - build"
  ansible.builtin.shell: >
    make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX={{ ansible_facts.env.HOME }}/.local &&
    make install
  environment:
    CCACHE_DISABLE: true
  args:
    chdir: ~/data/repos/neovim
    creates: ~/data/repos/neovim/build/bin/nvim
  timeout: 0
