---
- name: "[debian] Editor tools: ensure file watcher packages"
  become: true
  ansible.builtin.package:
    name: inotify-tools
    state: present

- name: "[debian] Dotfiles: ensure nvim pack folder"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "755"
  loop:
    - ~/.config
    - ~/.config/nvim
    - ~/.config/nvim/pack/

- name: "[debian] Editor tools: ensure nvim plugins"
  ansible.builtin.include_role:
    name: update-diff-capture
    tasks_from: git
  vars:
    update_diff_capture_scope: nvim-plugins
    update_diff_git_repo: "https://github.com/{{ item.repo }}"
    update_diff_git_dest: "{{ ansible_facts.env.HOME }}/.local/share/nvim/site/pack/plugins/{{ item.folder }}/{{ item.name | default(item.repo) | basename }}"
    update_diff_git_version: "{{ item.version | default('HEAD') }}"
    update_diff_git_single_branch: true
    update_diff_git_depth: 10
    update_diff_git_force: true
  loop: "{{ neovim_plugins }}"
  register: var_clone_nvim_plugins

- name: "[debian] Editor tools: build lookup of nvim plugin results by repo (init)"
  ansible.builtin.set_fact:
    nvim_plugin_result_by_repo: {}

- name: "[debian] Editor tools: build lookup of nvim plugin results by repo"
  ansible.builtin.set_fact:
    nvim_plugin_result_by_repo: "{{ nvim_plugin_result_by_repo | default({}) | combine({item.item.repo: item}) }}"
  loop: "{{ var_clone_nvim_plugins.results }}"

- name: "[debian] Editor tools: remove stale nvim plugins"
  ansible.builtin.file:
    path: ~/.local/share/nvim/site/pack/plugins/start/{{ item }}
    state: absent
  loop:
    - coc.nvim
    - plenary

- name: "[debian] Editor tools: clone universal ctags"
  ansible.builtin.include_role:
    name: update-diff-capture
    tasks_from: git
  vars:
    update_diff_capture_scope: editor-tools
    update_diff_git_repo: https://github.com/universal-ctags/ctags.git
    update_diff_git_dest: "{{ ansible_facts.env.HOME }}/data/repos/ctags"
    update_diff_git_depth: 1
    update_diff_git_version: master

- name: "[debian] Editor tools: ensure universal ctags"
  ansible.builtin.shell: |
    ./autogen.sh
    ./configure --prefix="$HOME/.local"
    make
    make install
  args:
    chdir: ~/data/repos/ctags
    creates: ~/.local/bin/ctags
