---
- name: "[debian] Dotfiles: ensure nvim pack folder"
  ansible.builtin.file:
    state: directory
    recurse: true
    path: ~/.config/nvim/pack/

- name: "[debian] Editor tools: ensure nvim plugins"
  ansible.builtin.git:
    repo: https://github.com/{{ item.repo }}
    dest: ~/.local/share/nvim/site/pack/plugins/{{ item.folder }}/{{ item.name | default(item.repo) | basename }}
    single_branch: true
    depth: 10
    version: "{{ item.version | default('HEAD') }}"
    force: true
  async: 1000
  poll: 0
  loop: "{{ neovim_plugins }}"

- name: "[debian] Editor tools: clone universal ctags"
  ansible.builtin.git:
    repo: https://github.com/universal-ctags/ctags.git
    dest: ~/repos/ctags
    depth: 1
    version: master

- name: "[debian] Editor tools: ensure universal ctags"
  ansible.builtin.shell: |
    ./autogen.sh
    ./configure --prefix="$HOME/.local"
    make
    make install
  args:
    chdir: ~/repos/ctags
    creates: ~/.local/bin/ctags
