---
- name: "[macosx] Dotfiles: ensure nvim pack folder"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "755"
  loop:
    - ~/.config
    - ~/.config/nvim
    - ~/.config/nvim/pack/

- name: "[macosx] Editor tools: ensure nvim plugins"
  ansible.builtin.git:
    repo: https://github.com/{{ item.repo }}
    dest: ~/.local/share/nvim/site/pack/plugins/{{ item.folder }}/{{ item.name | default(item.repo) | basename }}
    single_branch: true
    depth: 10
    version: "{{ item.version | default('HEAD') }}"
    force: true
  async: 1000
  poll: 0
  loop: "{{ neovim_plugins }}"
  register: var_async_clone_nvim_plugins

- name: "[macosx] Editor tools: wait for async clone nvim plugins"
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  register: var_job_result
  until: var_job_result is finished
  retries: 100
  delay: 10
  loop: "{{ var_async_clone_nvim_plugins.results }}"

- name: "[macosx] Editor tools: build lookup of nvim plugin results by repo (init)"
  ansible.builtin.set_fact:
    nvim_plugin_result_by_repo: {}

- name: "[macosx] Editor tools: build lookup of nvim plugin results by repo"
  ansible.builtin.set_fact:
    nvim_plugin_result_by_repo: "{{ nvim_plugin_result_by_repo | default({}) | combine({item.item.item.repo: item}) }}"
  loop: "{{ var_job_result.results }}"

- name: "[macosx] Editor tools: remove stale coc.nvim plugin"
  ansible.builtin.file:
    path: ~/.local/share/nvim/site/pack/plugins/start/coc.nvim
    state: absent
