---
- name: "[archlinux] Git tools: ensure diff tools"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - difftastic
      - git-delta

- name: "[archlinux] Git tools: remove stable lazygit package"
  become: true
  ansible.builtin.package:
    state: absent
    name: lazygit

- name: "[archlinux] Git tools: ensure lazygit from master"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/10-system-tools/tasks/install-local-aur-packages.archlinux.yml"
  vars:
    aur_local_packages: lazygit-git
