---
- block:
    - name: Ensure node
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 10-setup-node.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-10"]

- block:
    - name: Ensure rust
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 20-setup-rust.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux', 'debian']"
      loop_control:
        loop_var: task_file
  tags: ["20-20"]

- block:
    - name: Ensure python
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 30-setup-python.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-30"]

- block:
    - name: Ensure python tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 40-setup-python-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-40"]

- block:
    - name: Ensure neovim is installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 50-setup-neovim.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux', 'debian']"
      loop_control:
        loop_var: task_file
  tags: ["20-50"]

- block:
    - name: Ensure editor tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 60-setup-editor-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux', 'debian', 'macosx']"
      loop_control:
        loop_var: task_file
  tags: ["20-60"]

- block:
    - name: Ensure plantuml compiled jar is in location
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 80-setup-plantuml.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-80"]

- block:
    - name: Ensure git tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 90-setup-git-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-90"]

- block:
    - name: Setup terminal tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 100-setup-terminal-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux', 'debian']"
      loop_control:
        loop_var: task_file
  tags: ["20-100"]

- block:
    - name: Setup nvr tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 110-setup-nvr-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-110"]

- block:
    - name: Setup lua tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 120-setup-lua-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-120"]

- block:
    - name: Setup go tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 130-setup-go-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-130"]

- block:
    - name: Setup database tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 140-setup-database-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-140"]

- block:
    - name: Setup google tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 150-setup-google-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-150"]

- block:
    - name: Setup other tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 160-setup-other-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-160"]

- block:
    - name: Setup ai tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 170-setup-ai-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-170"]
