#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected_path=$1
else
    selected_path=$(find ~/work/gp/.bare ~/pjs ~/repos ~/courses ~/temp ~/issues ~/dotfiles ~/.local/share/Cryptomator/mnt ~/.local/share/nvim/site/pack/plugins/start ~/.local/share/nvim/site/pack/plugins/opt ~/.local/share/nvim/gp ~/external/work/cf/repos ~/external/repos ~/external/pjs -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected_path ]]; then
    exit 0
fi

selected_name=$(basename "$selected_path" | tr . _)
# Create a unique identifier from the full path
unique_id=$(echo -n "$selected_path" | sha256sum | head -c 8)
# Combine the directory name and unique identifier for the session name
session_identifier="${selected_name}_${unique_id}"

selected_path_escaped=$(echo $selected_path | sed -e 's/[]\/$*.^[]/_/g')
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    # create a new session when tmux is not running
    tmux new-session -s $session_identifier -c $selected_path
    exit 0
fi

if ! tmux has-session -t=$session_identifier 2> /dev/null; then
    # create new session in detached mode
    tmux new-session -ds $session_identifier -c $selected_path -x "$(tput cols)" -y "$(tput lines)"
    # set per-session env to define an nvim pipe
    tmux setenv -t $session_identifier CUSTOM_NVIM_LISTEN_ADDRESS "/tmp/$selected_path_escaped"
    # Check if current or parent directory is a git repository
    if [ -d "$selected_path/.git" ] || (cd "$selected_path" && git rev-parse --is-inside-work-tree >/dev/null 2>&1); then
      # open lazygit on a new window using TERM=xterm-256color to fix truecolor issues
      tmux new-window -t "=$session_identifier:1" -c "$selected_path"
      tmux send-keys -t "=$session_identifier:1" "TERM=xterm-256color lazygit" Enter
      # go back to first window
      tmux select-window -t "=$session_identifier:{start}"
    fi
fi

tmux switch-client -t $session_identifier
