#!/bin/sh
# Xsetup - run as root before the login dialog appears
# This file should be copied into /usr/share/sddm/scripts/Xsetup

snixembed --fork

# Save output into file
exec >/home/serranomorante/xsetup.out 2>&1

# Setup monitors
internal=$(xrandr | grep "DP.* connected" | cut -d " " -f 1)
external=$(xrandr | grep "HDMI.* connected" | cut -d " " -f 1)
if [[ $external != "" ]]; then
    # Turn off internal screen
    xrandr --output $internal --off
    # Set external monitor as primary
    xrandr --output $external --primary --mode 3440x1440 --rate 59.97
else
    xrandr --output $internal --primary --mode 1920x1080 --rate 120.21
fi

# Setup nvidia
# Set a max limit on the graphics gpu
nvidia-smi -lgc 139,300
# Under-clock the graphics memory
nvidia-settings -a "GPUMemoryTransferRateOffset[0x3]=-2000" -c :0
