# systemd ExecStartPre will replace these with their /dev/input/<id>
devices:
  - "keyd virtual keyboard"
  - "PFU Limited HHKB-Hybrid Keyboard"
  - "Logitech MX Keys"
  - "HHKB-Hybrid_1 Keyboard"
  - "ITE Tech. Inc. ITE Device(8910) Wireless Radio Control"

# fix keyboard rate
# https://github.com/jbensmann/mouseless/issues/7
startCommand: "configure-keyboard.sh"

# the default speed for mouse movement and scrolling
baseMouseSpeed: 950.0
baseScrollSpeed: 10.0

mouseAccelerationTime: 300.0
mouseAccelerationCurve: 2.0

mouseDecelerationTime: 100.0
mouseDecelerationCurve: 1.0

# the rest of the config defines the layers with their bindings
layers:
  # the first layer is active at start
  - name: initial
    bindings:
      # activate mouse layer
      leftctrl+rightctrl: layer mouse
  # a layer for mouse movement
  - name: mouse
    # when true, keys that are not mapped keep their original meaning
    passThrough: true
    # https://superuser.com/a/1593924
    enterCommand: "show_mouseless_osd.sh"
    exitCommand: "hide_mouseless_osd.sh"
    bindings:
      # quit mouse layer
      q: layer initial
      esc: layer initial
      # also quit mouse layer but this is used by keyd only
      leftalt+rightalt: layer initial
      # move cursor right
      l: move  1  0
      # move cursor left
      h: move -1  0
      # move cursor down
      j: move  0  1
      # move cursor up
      k: move  0 -1
      # r: reload-config
      p: scroll up
      n: scroll down
      u: scroll left
      o: scroll right
      r: speed 20.0
      w: speed 2.0
      v: speed 0.2
      f: button left
      d: button middle
      s: button right
