---
- name: "[archlinux] Markdown language: register texlive group" # exclude fontsextra to save disk space
  become: true
  ansible.builtin.shell: >
    set -o pipefail &&
    pacman -Sg texlive | grep -v fontsextra | cut -d " " -f 2
  changed_when: false
  register: texlive_group_pkgs

- name: "[archlinux] Markdown language: ensure packages"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - marksman
      - mdcat

- name: "[archlinux] Markdown language: ensure aur texlive"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ texlive_group_pkgs.stdout | regex_findall('(.*)\n') }}" # necessary to make pdflatex work

- name: "[archlinux] Markdown language: ensure xelatex is installed"
  become: true
  ansible.builtin.package:
    state: present
    name: texlive-xetex

- name: "[archlinux] Markdown language: ensure aur packages"
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    state: present
    name: mathjax
    aur_only: true

- name: "[archlinux] Markdown language: ensure npm packages"
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    global: true
    state: present
    executable: "{{ ansible_firejail_npm_executable }}"
  environment:
    ANSIBLE_FIREJAIL_NPM_NODE_VERSION: "{{ node_system_default_version }}"
    ANSIBLE_FIREJAIL_NPM_PREFIX: "{{ node_markdown_npm_prefix }}"
  loop: "{{ node_markdown_npm_packages }}"

- name: "[archlinux] Markdown language: symlink npm binaries"
  ansible.builtin.file:
    src: "{{ node_markdown_npm_prefix }}/bin/{{ item.1 }}"
    dest: "{{ node_user_bin_dir }}/{{ item.1 }}"
    state: link
  loop: "{{ node_markdown_npm_packages | subelements('bins') }}"

- name: "[archlinux] Markdown language: ensure virtualenv packages"
  ansible.builtin.pip:
    name:
      - pip
      - weasyprint
      - mdformat
      - mdformat-gfm
      - mdformat_footnote
      - mdformat-frontmatter
      - mdformat-web
      - mdformat-wikilink
    executable: "{{ ansible_facts.env.HOME }}/bin/ansible-firejail-pip"
    state: present
  environment:
    ANSIBLE_FIREJAIL_PIP_VENV: "{{ ansible_facts.env.HOME }}/data/apps/note-taking-tools/utilities/.venv"

- name: "[archlinux] Markdown language: symlink virtualenv packages"
  ansible.builtin.file:
    src: ~/data/apps/note-taking-tools/utilities/.venv/bin/{{ item }}
    dest: ~/bin/{{ item }}
    state: link
  loop:
    - mdformat
    - weasyprint
