---
- name: "[archlinux] Go language: ensure packages"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - gopls
      - delve

- name: "[archlinux] Go language: clone vscode-go"
  ansible.builtin.git:
    repo: https://github.com/golang/vscode-go
    executable: "{{ ansible_facts.env.HOME }}/dotfiles/utilities/bin/dotfiles-github-git"
    dest: ~/data/repos/vscode-go
    depth: 1
    single_branch: true
    version: v{{ vscode_go_version }}
  register: var_clone_vscode_go

- name: "[archlinux] Go language: stat vscode-go build marker"
  ansible.builtin.stat:
    path: ~/data/repos/vscode-go/extension/.ansible-vscode-go-build
  register: var_vscode_go_build_marker

- name: "[archlinux] Go language: install vscode-go npm packages"
  community.general.npm:
    path: "{{ ansible_facts.env.HOME }}/data/repos/vscode-go/extension"
    ci: true
    executable: "{{ ansible_firejail_npm_executable }}"
  environment:
    ANSIBLE_FIREJAIL_NPM_NODE_VERSION: "{{ node_system_default_version }}"
  changed_when: false
  when: var_clone_vscode_go.changed or not var_vscode_go_build_marker.stat.exists

- name: "[archlinux] Go language: build vscode-go"
  ansible.builtin.command:
    argv:
      - "{{ node_firejail_executable }}"
      - offline
      - "{{ ansible_facts.env.HOME }}/data/repos/vscode-go/extension"
      - --
      - "{{ node_system_default_node_path }}"
      - "{{ node_system_default_npm_path }}"
      - run
      - compile
  environment:
    NPM_CONFIG_IGNORE_SCRIPTS: "false"
  args:
    chdir: ~/data/repos/vscode-go/extension
  changed_when: false
  when: var_clone_vscode_go.changed or not var_vscode_go_build_marker.stat.exists

- name: "[archlinux] Go language: record vscode-go build marker"
  ansible.builtin.copy:
    content: "v{{ vscode_go_version }}\n"
    dest: ~/data/repos/vscode-go/extension/.ansible-vscode-go-build
    mode: "644"
  when: var_clone_vscode_go.changed or not var_vscode_go_build_marker.stat.exists
