---
- name: "[{{ user_os }}] Lua language: ensure LSP"
  become: true
  ansible.builtin.package:
    state: present
    name: lua-language-server

- name: "[{{ user_os }}] Lua language: ensure FORMATTERS"
  become: true
  ansible.builtin.package:
    state: present
    name: stylua
