---
- name: "[archlinux] Javascript language: ensure npm packages"
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    global: true
    state: present
    executable: "{{ ansible_firejail_npm_executable }}"
  environment:
    ANSIBLE_FIREJAIL_NPM_NODE_VERSION: "{{ node_system_default_version }}"
    ANSIBLE_FIREJAIL_NPM_PREFIX: "{{ node_javascript_npm_prefix }}"
  loop: "{{ node_javascript_npm_packages }}"

- name: "[archlinux] Javascript language: symlink npm binaries"
  ansible.builtin.file:
    src: "{{ node_javascript_npm_prefix }}/bin/{{ item.1 }}"
    dest: "{{ node_user_bin_dir }}/{{ item.1 }}"
    state: link
  loop: "{{ node_javascript_npm_packages | subelements('bins') }}"

- name: "[archlinux] Javascript language: ensure FORMATTERS (using aur)"
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    use: yay
    state: present
    name: prettierd

- name: "[archlinux] Javascript language: clone vscode-js-debug"
  ansible.builtin.git:
    repo: https://github.com/microsoft/vscode-js-debug.git
    dest: ~/data/repos/vscode-js-debug
    depth: 1
    force: true
    single_branch: true
    version: v{{ vscode_js_debug_version }}
  register: var_clone_vscode_js_debug

- name: "[archlinux] Javascript language: apply custom patch"
  ansible.builtin.command: git apply ~/dotfiles/assets/patches/vscode_js_debug_stderr.patch
  args:
    chdir: ~/data/repos/vscode-js-debug
  changed_when: false

- name: "[archlinux] Javascript language: stat vscode-js-debug build"
  ansible.builtin.stat:
    path: ~/data/repos/vscode-js-debug/dist/src/dapDebugServer.js
  register: var_stat_vscode_js_debug

- name: "[archlinux] Javascript language: install vscode-js-debug npm packages"
  community.general.npm:
    path: "{{ ansible_facts.env.HOME }}/data/repos/vscode-js-debug"
    ci: true
    executable: "{{ ansible_firejail_npm_executable }}"
  environment:
    ANSIBLE_FIREJAIL_NPM_NODE_VERSION: "{{ node_system_default_version }}"
  when: var_clone_vscode_js_debug.changed or not var_stat_vscode_js_debug.stat.exists

- name: "[archlinux] Javascript language: build vscode-js-debug"
  ansible.builtin.command:
    argv:
      - "{{ node_system_default_node_path }}"
      - "{{ node_system_default_npx_path }}"
      - gulp
      - dapDebugServer
  args:
    chdir: ~/data/repos/vscode-js-debug
  when: var_clone_vscode_js_debug.changed or not var_stat_vscode_js_debug.stat.exists
