---
- name: "[archlinux] Vim language: ensure local AUR LSP"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/10-system-tools/tasks/install-local-aur-packages.archlinux.yml"
  vars:
    aur_local_packages: vim-language-server
