---
- name: "[archlinux] Yaml language: ensure LSP"
  become: true
  ansible.builtin.package:
    state: present
    name: yamllint

- name: "[archlinux] Yaml language: ensure ansible-lint"
  ansible.builtin.command: uv tool install --python=3.12 ansible-lint
  args:
    creates: ~/.local/bin/ansible-lint
