---
- name: "[archlinux] Editor code generation: register binaries paths"
  ansible.builtin.command: which {{ executable }}
  register: binaries
  loop_control:
    loop_var: executable
  loop:
    - lua-language-server
    - gopls
    - gofmt
    - dlv
    - clangd
    - vscode-html-language-server
    - vscode-css-language-server
    - vscode-json-language-server
    - vscode-eslint-language-server
    - phpactor
    - marksman
  changed_when: false

- name: "[archlinux] Editor code generation: ensure binaries code-generation"
  ansible.builtin.blockinfile:
    dest: ~/.config/nvim/lua/serranomorante/binaries.lua
    create: true
    marker: "-- {mark} ANSIBLE MANAGED BLOCK"
    mode: "644"
    block: |
      return {
        {% for pkg_path in binaries.results -%}
          {{ pkg_path.executable | replace("-", "_") }} = function() return "{{ pkg_path.stdout }}" end,
        {% endfor %}
        system_default_node = function() return "{{ node_system_default_node_path }}" end,
        mcp_hub_executable = function() return "{{ node_user_bin_dir }}/mcp-hub" end,
        eslint_d_executable = function() return "{{ node_user_bin_dir }}/eslint_d" end,
        js_beautify_executable = function() return "{{ node_user_bin_dir }}/js-beautify" end,
        vscode_js_debug_dap_executable = function() return vim.env.HOME .. "/data/repos/vscode-js-debug/dist/src/dapDebugServer.js" end,
        cppdbg_dap_executable = function() return vim.env.HOME .. "/data/apps/lang-tools/cpptools/extension/debugAdapters/bin/OpenDebugAD7" end,
        pylsp = function() return vim.env.HOME .. "/bin/pylsp" end,
        bashdb_dap_executable = function() return vim.env.HOME .. "/data/apps/lang-tools/bash-debug-adapter" end,
        php_dap_executable = function() return "/usr/lib/node_modules/php-debug/out/phpDebug.js" end,
        debugpy_dap_executable = function() return vim.env.HOME .. "/data/apps/lang-tools/debugpy/.venv/bin/python" end,
        go_dap_executable = function() return vim.env.HOME .. "/data/repos/vscode-go/extension/dist/debugAdapter.js" end
      }
