---
- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 10-setup-c-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-10"]

- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 20-setup-lua-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-20"]

- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 30-setup-javascript-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-30"]

- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 40-setup-fish-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-40"]

- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 50-setup-bash-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-50"]

- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 60-setup-vim-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-60"]

- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 70-setup-python-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-70"]

- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 90-setup-yaml-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-90"]

- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 100-setup-markdown-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-100"]

- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 110-setup-html-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-110"]

- block:
    - name: Ensure language tools are installed
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 120-setup-php-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-120"]

- block:
    - name: Ensure assembly tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 130-setup-assembly-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-130"]

- block:
    - name: Ensure go tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 140-setup-go-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-140"]

- block:
    - name: Ensure editor code-generation
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 999-setup-editor-code-generation.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux', 'debian']"
      loop_control:
        loop_var: task_file
  tags: ["30-999"]
