monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-Focusrite_Scarlett_4i4_4th_Gen_.*"
      }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
      }
    }
  },
  {
    matches = [
      {
        node.name = "~alsa_input.usb-Focusrite_Scarlett_4i4_4th_Gen_.*"
      }
      {
        node.name = "~alsa_output.usb-Focusrite_Scarlett_4i4_4th_Gen_.*"
      }
    ]
    actions = {
      update-props = {
        node.pause-on-idle = true
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_input.usb-Focusrite_Scarlett_4i4_4th_Gen_.*-00.pro-input-0"
      }
    ]
    actions = {
      update-props = {
        node.name = "alsa_input.usb-Focusrite_Scarlett_4i4_4th_Gen.pro-input-0"
      }
    }
  }
]
