wireplumber.components = [
  {
    name = device/set-integrated-speakers-default-volume.lua, type = script/lua
    provides = custom.integrated-speakers-default-volume
  }
]

wireplumber.profiles = {
  main = {
    custom.integrated-speakers-default-volume = required
  }
}
