---
- name: "[dotfiles-markers] Validate marker record-many variables"
  ansible.builtin.assert:
    that:
      - dotfiles_marker_items is defined
    quiet: true

- name: "[dotfiles-markers] Set marker record-many defaults"
  ansible.builtin.set_fact:
    dotfiles_marker_many_mode_default: "{{ dotfiles_marker_mode | default('644') }}"
    dotfiles_marker_many_notify_default: "{{ dotfiles_marker_notify | default([]) }}"

- name: "[dotfiles-markers] Record marker items"
  ansible.builtin.include_tasks: record-many-one.yml
  loop: "{{ dotfiles_marker_items }}"
  loop_control:
    loop_var: dotfiles_marker_many_entry
    label: "{{ dotfiles_marker_many_entry.name }}"
