require("serranomorante.globals")
require("serranomorante.set")
require("serranomorante.remap")
require("serranomorante.autocmds")
require("serranomorante.remote_kitty_focus").setup()
require("serranomorante.vim_register_clipboard").setup()
