[localhost]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python

[arch_user]
arch-user

[arch_chroot]
arch-chroot

[archsystem]
arch-install

[phone]
phone

[reader]
reader

[macos]
macos

[phone2]
phone2
