---
- hosts: localhost,all
  gather_facts: false
  vars:
    is_x_display_session: false

  pre_tasks:
    - name: "Setup playbook: get command arguments used to invoke ansible"
      get_argv:
      register: var_argv
      tags: always

    - name: "Setup playbook: gather facts conditionally"
      ansible.builtin.gather_facts:
      when:
        - inventory_hostname == 'localhost' or inventory_hostname == 'phone2' or 'arch_user' in group_names
      tags: always

    - name: "Setup playbook: populate service facts"
      ansible.builtin.service_facts:
      when:
        - inventory_hostname == 'localhost' or inventory_hostname == 'phone2' or 'arch_user' in group_names
      tags: always

    - name: "Setup playbook: set user_os"
      ansible.builtin.set_fact:
        user_os: "{{ ansible_facts.distribution | lower | replace(' ', '') }}"
      when: ansible_facts.distribution is defined
      tags: always

    - name: "Setup roles: set var"
      ansible.builtin.stat:
        path: "{{ item }}"
      register: var_role_exists
      loop:
        - ../for-my-eyes-only/playbooks/roles/60-for-my-eyes-only/tasks/main.yml
        - ../for-my-eyes-only/playbooks/roles/70-for-my-eyes-only/tasks/main.yml
        - ../for-my-eyes-only/playbooks/roles/80-for-my-eyes-only/tasks/main.yml
      tags: always

    - name: "Setup roles: set fact"
      ansible.builtin.set_fact:
        fact_roles: "{{ fact_roles | default({}) | combine({file: item.stat.exists}) }}"
      vars:
        file: "{{ item.item }}"
      loop: "{{ var_role_exists.results }}"
      tags: always

    - name: "[archlinux] Nvidia tools: check valid x session"
      ansible.builtin.shell: xhost >& /dev/null
      register: var_is_x_display_session
      changed_when: true
      ignore_errors: true
      tags: always

    - name: "[archlinux] Nvidia tools: set x display fact"
      ansible.builtin.set_fact:
        is_x_display_session: "{{ var_is_x_display_session.rc == 0 }}"
      tags: always

  tasks:
    - block:
        - name: Run 10-system-tools role
          ansible.builtin.import_role:
            name: 10-system-tools
          tags: [10-system-tools]

        - name: Run 20-dev-tools role
          ansible.builtin.import_role:
            name: 20-dev-tools
          tags: [20-dev-tools]

        - name: Run 30-lang-tools role
          ansible.builtin.import_role:
            name: 30-lang-tools
          tags: [30-lang-tools]

        - name: Run 40-PKM role
          ansible.builtin.import_role:
            name: 40-PKM
          tags: [40-PKM]

        - name: Run 50-cloud-tools role
          ansible.builtin.import_role:
            name: 50-cloud-tools
          tags: [50-cloud-tools]

        - name: Include 60-for-my-eyes-only if present
          ansible.builtin.include_role:
            name: ../for-my-eyes-only/playbooks/roles/60-for-my-eyes-only # noqa role-name[path]
            apply:
              tags: 60-for-my-eyes-only
          tags: always
          when: fact_roles['../for-my-eyes-only/playbooks/roles/60-for-my-eyes-only/tasks/main.yml']

        - name: Include 70-for-my-eyes-only if present
          ansible.builtin.include_role:
            name: ../for-my-eyes-only/playbooks/roles/70-for-my-eyes-only # noqa role-name[path]
            apply:
              tags: 70-for-my-eyes-only
          tags: always
          when: fact_roles['../for-my-eyes-only/playbooks/roles/70-for-my-eyes-only/tasks/main.yml']

        - name: Include 80-for-my-eyes-only if present
          ansible.builtin.include_role:
            name: ../for-my-eyes-only/playbooks/roles/80-for-my-eyes-only # noqa role-name[path]
            apply:
              tags: 80-for-my-eyes-only
          tags: always
          when: fact_roles['../for-my-eyes-only/playbooks/roles/80-for-my-eyes-only/tasks/main.yml']
      always:
        - name: Flush handlers before AUR teardown
          ansible.builtin.meta: flush_handlers
          when:
            - user_os is defined
            - user_os in ['archlinux']
            - inventory_hostname == 'localhost' or inventory_hostname == 'phone2' or 'arch_user' in group_names
          tags:
            - setup
            - 10-system-tools

        - name: Remove temporary AUR passwordless sudoers rule
          ansible.builtin.import_tasks: roles/10-system-tools/tasks/teardown-aur-passwordless.archlinux.yml
          when:
            - user_os is defined
            - user_os in ['archlinux']
            - inventory_hostname == 'localhost' or inventory_hostname == 'phone2' or 'arch_user' in group_names
          tags:
            - setup
            - 10-system-tools
