---
- name: "[archlinux] Yabridge tools: ensure yabridge is installed"
  ansible.builtin.unarchive:
    src: https://github.com/robbert-vdh/yabridge/releases/download/{{ arch_yabridge_version }}/yabridge-{{ arch_yabridge_version }}.tar.gz
    dest: ~/.local/share/
    remote_src: true
    creates: ~/.local/share/yabridge/.ansible-yabridge-{{ arch_yabridge_version }}

- name: "[archlinux] Yabridge tools: record yabridge marker"
  ansible.builtin.copy:
    content: "{{ arch_yabridge_version }}\n"
    dest: ~/.local/share/yabridge/.ansible-yabridge-{{ arch_yabridge_version }}
    mode: "644"
