---
- name: "Setup virtualbox: ensure packages"
  aur:
    use: yay
    state: present
    name:
      - virtualbox
      - virtualbox-host-modules-lts
      - virtualbox-guest-iso # https://wiki.archlinux.org/title/VirtualBox#Guest_additions

# https://wiki.archlinux.org/title/VirtualBox#Accessing_host_USB_devices_in_guest
- name: "Setup virtualbox: ensure vboxusers group"
  become: true
  ansible.builtin.group:
    state: present
    name: vboxusers

- name: "Setup virtualbox: append user to group"
  become: true
  ansible.builtin.user:
    append: true
    groups: vboxusers
    name: "{{ ansible_env.USER }}"
