---
- name: "[archlinux] Setup virtualbox: ensure packages"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - meson
      - ninja

- name: "[archlinux] Setup virtualbox: ensure aur packages"
  aur:
    use: yay
    state: present
    name:
      - cryptomator
      - virtualbox
      - virtualbox-host-modules-lts
      - virtualbox-guest-iso # https://wiki.archlinux.org/title/VirtualBox#Guest_additions

# https://wiki.archlinux.org/title/VirtualBox#Accessing_host_USB_devices_in_guest
- name: "[archlinux] Setup virtualbox: ensure vboxusers group"
  become: true
  ansible.builtin.group:
    state: present
    name: vboxusers

- name: "[archlinux] Setup virtualbox: append user to group"
  become: true
  ansible.builtin.user:
    append: true
    groups: vboxusers
    name: "{{ ansible_env.USER }}"

- name: "[archlinux] Setup virtualbox: clone fuse3 arch package"
  ansible.builtin.git:
    repo: https://gitlab.archlinux.org/archlinux/packaging/packages/fuse3
    dest: ~/external/repos/fuse3
    version: "{{ arch_fuse_version }}"
    force: true
    single_branch: true
    depth: 1

- name: "[archlinux] Setup virtualbox: downgrade fuse3 arch package"
  aur:
    use: makepkg
    name: fuse3
    state: present
    local_pkgbuild: ~/external/repos/fuse3
