---
- name: "[archlinux] Persistence tools: ensure valkey packages"
  become: true
  ansible.builtin.package:
    state: present
    name: valkey

- name: "[archlinux] Persistence tools: enable valkey service and ensure is not masked"
  become: true
  ansible.builtin.systemd_service:
    name: valkey.service
    enabled: true
    masked: false

- name: "[archlinux] Persistence tools: ensure virtualenv packages"
  ansible.builtin.include_role:
    name: update-diff-capture
    tasks_from: pip
  vars:
    update_diff_capture_scope: persistence-tools
    update_diff_pip_venv: "{{ ansible_facts.env.HOME }}/data/apps/persistence-tools/.venv"
    update_diff_pip_executable: "{{ ansible_facts.env.HOME }}/bin/ansible-firejail-pip"
    update_diff_pip_state: latest
    update_diff_pip_packages:
      - name: pip
      - name: redis
      - name: ansible

- name: "[archlinux] Persistence tools: symlink virtualenv ansible"
  ansible.builtin.file:
    src: ~/data/apps/persistence-tools/.venv/bin/{{ item.bin_name }}
    dest: ~/bin/{{ item.symlink_name }}
    state: link
  loop:
    - bin_name: ansible
      symlink_name: vansible
    - bin_name: ansible-playbook
      symlink_name: vansible-playbook
    - bin_name: ansible-vault
      symlink_name: vansible-vault
    - bin_name: ansible-galaxy
      symlink_name: vansible-galaxy
