---
- name: "[archlinux] Setup encryption tools: enable services"
  ansible.builtin.systemd_service:
    scope: user
    name: ssh-agent.service
    state: started
    enabled: true
    masked: false

# https://wiki.archlinux.org/title/SSH_keys#Start_ssh-agent_with_systemd_user
- name: "[archlinux] Setup encryption tools: setup shell startup scripts"
  ansible.builtin.blockinfile:
    marker: "## {mark} ANSIBLE MANAGED BLOCK - SETUP ENCRYPTION"
    dest: "{{ item.script }}"
    create: true
    mode: "744"
    block: |
      {% if 'dot-bashrc' in item.script %}
      export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
      {% endif %}
  loop:
    - { script: ~/dotfiles/home/dot-bashrc }
