---
- name: "[archlinux] AUR: ensure local review/build dependencies"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - base-devel
      - devtools
      - git

- name: "[archlinux] AUR: remove legacy aur_builder passwordless pacman rule"
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/11-install-aur_builder
    state: absent

- name: "[archlinux] AUR: ensure local package repository directory"
  become: true
  ansible.builtin.file:
    path: "{{ arch_aur_local_repo_path }}"
    state: directory
    owner: root
    group: wheel
    mode: "2775"

- name: "[archlinux] AUR: ensure clean chroot parent directory"
  become: true
  ansible.builtin.file:
    path: "{{ arch_aur_local_chroot_path }}"
    state: directory
    owner: root
    group: wheel
    mode: "2775"

- name: "[archlinux] AUR: check local package repository database"
  ansible.builtin.stat:
    path: "{{ arch_aur_local_repo_path }}/{{ arch_aur_local_repo_name }}.db.tar.gz"
  register: var_arch_aur_local_repo_db

- name: "[archlinux] AUR: initialize empty local package repository database"
  become: true
  ansible.builtin.command:
    argv:
      - repo-add
      - "{{ arch_aur_local_repo_path }}/{{ arch_aur_local_repo_name }}.db.tar.gz"
  when: not var_arch_aur_local_repo_db.stat.exists
  changed_when: true

- name: "[archlinux] AUR: ensure local package repository files are group writable"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: wheel
    mode: "664"
  loop:
    - "{{ arch_aur_local_repo_path }}/{{ arch_aur_local_repo_name }}.db"
    - "{{ arch_aur_local_repo_path }}/{{ arch_aur_local_repo_name }}.db.tar.gz"
    - "{{ arch_aur_local_repo_path }}/{{ arch_aur_local_repo_name }}.files"
    - "{{ arch_aur_local_repo_path }}/{{ arch_aur_local_repo_name }}.files.tar.gz"
  when: not var_arch_aur_local_repo_db.stat.exists

- name: "[archlinux] AUR: configure pacman local package repository"
  become: true
  ansible.builtin.blockinfile:
    dest: /etc/pacman.conf
    insertafter: EOF
    marker: "## {mark} ANSIBLE MANAGED BLOCK - AUR LOCAL REPOSITORY"
    block: |
      [{{ arch_aur_local_repo_name }}]
      SigLevel = Optional TrustAll
      Server = file://{{ arch_aur_local_repo_path }}
