---
- name: "[otherlinux] Dotfiles: ensure stow installed"
  ansible.builtin.command: >
    pkg install -y
    stow
  changed_when: false

- name: "[otherlinux] Dotfiles: apply stow"
  ansible.builtin.shell: >
    stow --dotfiles
    gnupg
  args:
    chdir: ~/dotfiles
  changed_when: false
