---
- name: "[otherlinux] Dotfiles: ensure stow installed"
  ansible.builtin.command: pkg install -y {{ item }}
  loop:
    - stow
  changed_when: false

- name: "[otherlinux] Dotfiles: download dotfiles"
  ansible.builtin.git:
    repo: https://github.com/serranomorante/dotfiles.git
    dest: ~/dotfiles
    force: true
    depth: 1
    version: main

- name: "[otherlinux] Dotfiles: apply stow"
  ansible.builtin.shell: >
    stow --dotfiles
    gnupg
  args:
    chdir: ~/dotfiles
  changed_when: false
