---
- name: "[archlinux] Notification utilities: ensure several grep packages"
  ansible.builtin.package:
    state: present
    name:
      - dunst
      - libnotify

- name: "[archlinux] Notification utilities: ensure dunst service"
  ansible.builtin.systemd_service:
    scope: user
    name: dunst.service
    state: started
    enabled: true
    masked: false
