---
- name: "[archlinux] Notification utilities: ensure several grep packages"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - remind
      - dunst
      - libnotify
  notify: handler_restart_remind_service

- name: "[archlinux] Notification utilities: ensure local AUR packages"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/10-system-tools/tasks/install-local-aur-packages.archlinux.yml"
  vars:
    aur_local_packages: tcllib

- name: "[archlinux] Notification utilities: ensure dunst service"
  ansible.builtin.systemd_service:
    scope: user
    name: dunst.service
    enabled: true
    masked: false

- name: "[archlinux] Notification utilities: ensure remind state folder"
  ansible.builtin.file:
    path: ~/.local/state/remind
    state: directory
    mode: "755"
  notify: handler_restart_remind_service

- name: "[archlinux] Notification utilities: ensure remind config folder"
  ansible.builtin.file:
    path: ~/.config/remind
    state: directory
    mode: "755"
  notify: handler_restart_remind_service

- name: "[archlinux] Notification utilities: install remind helper file"
  ansible.builtin.copy:
    src: "{{ ansible_facts.env.HOME }}/dotfiles/PKM/remind/00-helpers.rem"
    dest: ~/.config/remind/00-helpers.rem
    remote_src: true
    follow: false
    mode: "644"
  notify: handler_restart_remind_service

- name: "[archlinux] Notification utilities: check legacy remind oncefile"
  ansible.builtin.stat:
    path: ~/.config/remind/oncefile
  register: var_remind_legacy_oncefile

- name: "[archlinux] Notification utilities: check remind state oncefile"
  ansible.builtin.stat:
    path: ~/.local/state/remind/oncefile
  register: var_remind_state_oncefile

- name: "[archlinux] Notification utilities: migrate remind oncefile"
  ansible.builtin.command:
    argv:
      - mv
      - "{{ ansible_facts['user_dir'] }}/.config/remind/oncefile"
      - "{{ ansible_facts['user_dir'] }}/.local/state/remind/oncefile"
  when:
    - var_remind_legacy_oncefile.stat.exists
    - not var_remind_state_oncefile.stat.exists
  notify: handler_restart_remind_service

- name: "[archlinux] Notification utilities: remove legacy remind oncefile"
  ansible.builtin.file:
    path: ~/.config/remind/oncefile
    state: absent
  when:
    - var_remind_legacy_oncefile.stat.exists
    - var_remind_state_oncefile.stat.exists
  notify: handler_restart_remind_service

- name: "[archlinux] Notification utilities: ensure dbus-1 servics folder"
  # See: https://dunst-project.org/faq/
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "755"
  loop:
    - ~/.local/share/dbus-1
    - ~/.local/share/dbus-1/services

- name: "[archlinux] Notification utilities: ensure dunst as default notification daemon"
  # See: https://dunst-project.org/faq/
  # And: https://github.com/dunst-project/dunst/issues/363
  ansible.builtin.file:
    src: /usr/share/dbus-1/services/{{ default_notification_daemon | default('org.knopwob.dunst.service') }}
    dest: "{{ ansible_facts.env.HOME }}/.local/share/dbus-1/services/org.freedesktop.Notifications.service"
    state: link
    force: true
