---
- name: "Upgrade cloud tools: stop tools"
  ansible.builtin.shell: app-{{ cloud_tool }} stop
  loop: "{{ cloud_tools }}"
  loop_control:
    loop_var: cloud_tool
  tags: [never, slow]

- name: "Upgrade cloud tools: upgrade tools"
  ansible.builtin.shell: app-{{ cloud_tool }} upgrade
  loop: "{{ cloud_tools }}"
  loop_control:
    loop_var: cloud_tool
  tags: [never, slow]

- name: "Upgrade cloud tools: start tools"
  ansible.builtin.shell: app-{{ cloud_tool }} start
  loop: "{{ cloud_tools }}"
  loop_control:
    loop_var: cloud_tool
  tags: [never, slow]
